로그인 및 회원가입 기능 추가
allwagelab/client pull request #2
Opened 2024-12-22 11:58 UTC by emmayoo

feat: 로그인/회원가입/이메일 찾기/비밀번호 찾기 (초안)
- tanstack/react-query, react-hook-form, zod, emotion 라이브러리 추가
- 로그인, 회원가입, 이메일 찾기, 비밀번호 찾기 페이지 구현
- 회원가입 모달 (react-portal) 구현

2024-12-23 12:12 UTC, createhb21 requested changes
👍 수고하셨습니다 👍

2024-12-23 12:12 UTC, createhb21 commented on web/src/components/auth/SignupModal/index.tsx
> +      throw error
여기서 에러 던져지면 어떻게 되나요?

2025-01-07 05:54 UTC, createhb21 reviewed
수고하셨습니다 👍
이번 피쳐 작업량이 많았는데 열심히 해주셔서 감사합니다 ☺️

2025-01-07 05:54 UTC, createhb21 commented on web/eslint.config.js
프로젝트 전반적으로 biome 사용중이라서 web 내부에 eslint가 필요없긴 한데
우선 이 PR에서는 머지하고 따로 PR 빼서 관련 작업 할게요

2025-01-07 05:54 UTC, createhb21 commented on web/.prettierrc
프리티어 관련 설정도 프로젝트 root에서 관리하는게 맞고,
biome 사용하는중이라 프리티어 설정은 없어도 되긴해요!

이것도 새로운 브렌치에서 작업할게요

2025-01-07 05:54 UTC, createhb21 commented on web/package.json
> +    "eslint-plugin-import": "^2.31.0",
동일

2025-01-07 05:54 UTC, createhb21 commented on web/package.json
> +    "prettier": "^3.4.2",
동일

2025-01-07 05:54 UTC, createhb21 commented on web/src/App.tsx
> +    if (localStorage.getItem('autoLogin') !== 'Y') {
persist를 이용해서 이미 로컬스토리지와 연동한 zustand 훅을 사용중인데
이 로직을 넣어야하나요? 
만약 넣어야한다면 auth관련된 상태와 로직들을 한군데서 모아서 관리하는게 좋을 것 같아요!

2025-01-07 05:54 UTC, createhb21 commented on web/src/apis/auth.ts
> +      throw new Error('이메일 또는 비밀번호를 확인해 주세요')
이러한 경우에는 constants에 에러 메시지들을 정의하고 사용하는게 좋습니다!

2025-01-07 05:54 UTC, createhb21 commented on web/src/apis/auth.ts
> +      if (error.response.status === 400) {
동일.
한군데서 에러의 status를 정의하고 갖고와서 사용하는 방식이 좋아요

2025-01-07 05:54 UTC, createhb21 commented on web/src/components/auth/SignupModal/BusinessForm.tsx
> +  const [isBusinessNumberVerified, setIsBusinessNumberVerified] = useState(false)
```js
const verification = useVerification({ setError, clearErrors })
```

다음부터는 위처럼 비즈니스 로직을 분리해서 사용하면 좋을 것 같아요.
각 부분의 책임이 명확해지는 장점이 있어요!

2025-01-07 05:54 UTC, createhb21 commented on web/src/components/ui/Modal/index.tsx
> +  useEffect(() => {
공용 훅으로 따로 빼도 좋을 것 같아요
ex. `useKeyTrap()`

2025-01-07 05:54 UTC, createhb21 commented on web/src/hooks/useAxiosPrivate.ts
> +  const refresh = useRefreshToken()
refresh가 refreshToken을 의미하는건지 refresh 함수를 의미하는건지 명확하지 않은 것 같아요!

2025-01-07 05:54 UTC, createhb21 commented on web/src/hooks/useAxiosPrivate.ts
인터셉터는 앱 시작시 네트워크 계층에서 한 번만 설정되면 되고 컴포넌트 생명주기와 무관하게 동작해서 훅으로 관리할 이유가 없을것같아요.

우선 지금은 이렇게 머지하고, 앞으로 더 나은 방법으로 개선해봐요!

2025-01-07 05:54 UTC, createhb21 commented on web/src/hooks/useLogin.ts
> +      if (onSuccess) {
navigate 이후에 props로 받은 onSuccess가 동작하면
예상치못한 사이드이펙트가 생길 수 있어요.

콜백을 먼저 실행하고 navigate하는게 좋아보여요!

2025-01-07 05:54 UTC, createhb21 commented on web/src/hooks/useTimer.ts
> +  }, [isRunning, onEnd])
nit: 심화과정
SetInterval은, 이벤트 루프에 들어올때까지가 정해진 시간을 사용하고, 콜스택이 비어진다음에 실행하기때문에 ms +알파초가 든다고 해요

조금 더 세밀한 초설정을
하려면 requestAminationFrame 콜백함수로 이용하는것도 좋습니다

2025-01-07 05:54 UTC, createhb21 commented on web/src/lib/constants.ts
`/constants/regex.ts` 로 빼는게 좋을것같아요

2025-01-07 05:54 UTC, createhb21 commented on web/src/lib/utils.ts
동일.
`/utils/format.ts` 으로 분리

2025-01-07 05:54 UTC, createhb21 commented on web/src/mocks/auth.ts
```ts
export const MOCK_DB = {
  BUSINESS_NUMBERS: ['123-45-67890'],
  PHONE_NUMBERS: ['010-1234-5678'],
  VALID_VERIFICATION_CODE: '1234',
  TEST_EMAIL: 'test@test.com',
  TEST_PASSWORD: 'test1234!'
}

// utils/mock.ts
export const createMockURL = (url: string) => {
  const baseURL = import.meta.env.VITE_BASE_URL
  const fullURL = new URL(url, baseURL)
  return fullURL.href
}

export const createSuccessResponse = (data?: any) => {
  return data 
    ? HttpResponse.json({ data }) 
    : new HttpResponse(null, { status: 201 })
}

export const createErrorResponse = (status = 401) => {
  return new HttpResponse(null, { status })
}
```

그리고 비즈니스 도메인 별로 핸들러는 분리해주는게 좋긴 할것같아요~!

2025-01-07 12:05 UTC, emmayoo commented on web/eslint.config.js
제가 eslint에 추가한 부분은 import order 뿐이긴한데, 이것뿐만 아니라 eslint 기능을 biome 로 대체하고 지우시겠다는 것이죠? 넵! 감사합니다 :)

2025-01-07 12:35 UTC, emmayoo commented on web/src/App.tsx
> +    if (localStorage.getItem('autoLogin') !== 'Y') {
오.. 그 생각은 안 해봤어요. onRehydrateStorage 써서 수정했습니다. 👍

2025-01-07 12:52 UTC, emmayoo commented on web/src/components/ui/Modal/index.tsx
> +  useEffect(() => {
useKeyEscape hook으로 뺐습니다.

2025-01-08 11:45 UTC, emmayoo commented
코드 리뷰 감사합니다. 남은 부분은 새 PR에서 이어서 하겠습니다.

* 디자인
* 에러 처리 및 메시지 constants로 분리
* 비즈니스 도메인별 핸들러 분리
* useTimer (requestAnimationFrame 활용)
* 리프레시 토큰을 사용한 액세스 토큰 갱신

2025-01-08 11:45 UTC, merged